version: '3'
services:
  db:
    image: postgres:latest
    restart: always
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    env_file: .env
    ports:
      - "5432:5432"
  opensearch:
    image: opensearchproject/opensearch:latest
    volumes:
      - os-data:/usr/share/opensearch/data
    environment:
      - discovery.type=single-node
      - plugins.security.disabled=true
    ports:
      - "9200:9200"
  cg-web:
    build: .
    restart: always
    links:
      - db
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    env_file: .env
    volumes:
      - app-storage:/rails/storage
    ports:
      - "3000:3000"
    depends_on:
      - db
      - opensearch
volumes:
  postgres_data: {}
  app-storage: {}
  os-data: {}
